// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `jugo_node_callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.node.callback;

public interface _NodeCallbackOperationsNC
{
    boolean invite(String taskId, String starter, String algorithmId, int maxOfParticipants, String[] takers, String[] resultReceiverList, String[] args);

    void allReady(String taskId, net.platon.vm.slice.common.NodeCommunicateInfo[] nodeCommunicateInfoList);

    void error(String taskId, net.platon.vm.slice.common.ErrorEnum error);

    void inputData(String taskId, String fromUser, byte[] data);

    void result(String taskId, byte[] data);
}
