// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `jugo_proxy_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.proxy.service;

public interface ProxySessionPrx extends Glacier2.SessionPrx
{
    public void setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo)
        throws net.platon.vm.slice.common.RpcException;

    public void setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, java.util.Map<String, String> __ctx)
        throws net.platon.vm.slice.common.RpcException;

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, Ice.Callback __cb);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, Callback_ProxySession_setNodeCallback __cb);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, java.util.Map<String, String> __ctx, Callback_ProxySession_setNodeCallback __cb);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, 
                                                 net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, 
                                                 net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, 
                                                 net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setNodeCallback(net.platon.vm.slice.node.callback.NodeCallbackPrx cb, 
                                                 net.platon.vm.slice.common.NodeCommunicateInfo nodeCommunicateInfo, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public void end_setNodeCallback(Ice.AsyncResult __result)
        throws net.platon.vm.slice.common.RpcException;

    public String invite(String roomId, String algorithmId, String starter, String[] takerList, String[] resultReceiverList, String[] args)
        throws net.platon.vm.slice.common.RpcException;

    public String invite(String roomId, String algorithmId, String starter, String[] takerList, String[] resultReceiverList, String[] args, java.util.Map<String, String> __ctx)
        throws net.platon.vm.slice.common.RpcException;

    public Ice.AsyncResult begin_invite(String roomId, String algorithmId, String starter, String[] takerList, String[] resultReceiverList, String[] args);

    public Ice.AsyncResult begin_invite(String roomId, String algorithmId, String starter, String[] takerList, String[] resultReceiverList, String[] args, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_invite(String roomId, String algorithmId, String starter, String[] takerList, String[] resultReceiverList, String[] args, Ice.Callback __cb);

    public Ice.AsyncResult begin_invite(String roomId, String algorithmId, String starter, String[] takerList, String[] resultReceiverList, String[] args, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_invite(String roomId, String algorithmId, String starter, String[] takerList, String[] resultReceiverList, String[] args, Callback_ProxySession_invite __cb);

    public Ice.AsyncResult begin_invite(String roomId, String algorithmId, String starter, String[] takerList, String[] resultReceiverList, String[] args, java.util.Map<String, String> __ctx, Callback_ProxySession_invite __cb);

    public Ice.AsyncResult begin_invite(String roomId, 
                                        String algorithmId, 
                                        String starter, 
                                        String[] takerList, 
                                        String[] resultReceiverList, 
                                        String[] args, 
                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_invite(String roomId, 
                                        String algorithmId, 
                                        String starter, 
                                        String[] takerList, 
                                        String[] resultReceiverList, 
                                        String[] args, 
                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_invite(String roomId, 
                                        String algorithmId, 
                                        String starter, 
                                        String[] takerList, 
                                        String[] resultReceiverList, 
                                        String[] args, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_invite(String roomId, 
                                        String algorithmId, 
                                        String starter, 
                                        String[] takerList, 
                                        String[] resultReceiverList, 
                                        String[] args, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public String end_invite(Ice.AsyncResult __result)
        throws net.platon.vm.slice.common.RpcException;

    public void forward(String taskId, String fromUser, String toUser, byte[] data)
        throws net.platon.vm.slice.common.RpcException;

    public void forward(String taskId, String fromUser, String toUser, byte[] data, java.util.Map<String, String> __ctx)
        throws net.platon.vm.slice.common.RpcException;

    public Ice.AsyncResult begin_forward(String taskId, String fromUser, String toUser, byte[] data);

    public Ice.AsyncResult begin_forward(String taskId, String fromUser, String toUser, byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forward(String taskId, String fromUser, String toUser, byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_forward(String taskId, String fromUser, String toUser, byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_forward(String taskId, String fromUser, String toUser, byte[] data, Callback_ProxySession_forward __cb);

    public Ice.AsyncResult begin_forward(String taskId, String fromUser, String toUser, byte[] data, java.util.Map<String, String> __ctx, Callback_ProxySession_forward __cb);

    public Ice.AsyncResult begin_forward(String taskId, 
                                         String fromUser, 
                                         String toUser, 
                                         byte[] data, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forward(String taskId, 
                                         String fromUser, 
                                         String toUser, 
                                         byte[] data, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_forward(String taskId, 
                                         String fromUser, 
                                         String toUser, 
                                         byte[] data, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forward(String taskId, 
                                         String fromUser, 
                                         String toUser, 
                                         byte[] data, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_forward(Ice.AsyncResult __result)
        throws net.platon.vm.slice.common.RpcException;

    public void result(String taskId, int code, byte[] data)
        throws net.platon.vm.slice.common.RpcException;

    public void result(String taskId, int code, byte[] data, java.util.Map<String, String> __ctx)
        throws net.platon.vm.slice.common.RpcException;

    public Ice.AsyncResult begin_result(String taskId, int code, byte[] data);

    public Ice.AsyncResult begin_result(String taskId, int code, byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_result(String taskId, int code, byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_result(String taskId, int code, byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_result(String taskId, int code, byte[] data, Callback_ProxySession_result __cb);

    public Ice.AsyncResult begin_result(String taskId, int code, byte[] data, java.util.Map<String, String> __ctx, Callback_ProxySession_result __cb);

    public Ice.AsyncResult begin_result(String taskId, 
                                        int code, 
                                        byte[] data, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_result(String taskId, 
                                        int code, 
                                        byte[] data, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_result(String taskId, 
                                        int code, 
                                        byte[] data, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_result(String taskId, 
                                        int code, 
                                        byte[] data, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_result(Ice.AsyncResult __result)
        throws net.platon.vm.slice.common.RpcException;
}
