// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `jugo_proxy_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.proxy.service;

public interface ProxySession extends Ice.Object,
                                      _ProxySessionOperations, _ProxySessionOperationsNC,
                                      Glacier2.Session
{
    public static final String ice_staticId = "::service::ProxySession";

    public static final long serialVersionUID = -1031639927L;
}
