// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon.service;

public interface _NodeChannelSessionOperations
{
    void invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Current __current);

    void _notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Current __current);

    int invite2(TaskParams taskparams, Ice.Current __current);

    int notify2(TaskParams taskparams, Ice.Current __current);

    void ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Current __current);

    void inputData(String taskId, String fromUser, byte[] data, Ice.Current __current);

    void input(byte[] data, Ice.Current __current);

    void error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, Ice.Current __current);
}
