// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon.service;

public abstract class _TaskSessionDisp extends Ice.ObjectImpl implements TaskSession
{
    protected void
    ice_copyStateFrom(Ice.Object __obj)
        throws java.lang.CloneNotSupportedException
    {
        throw new java.lang.CloneNotSupportedException();
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::platon::service::TaskSession"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public final net.platon.vm.slice.platon.ErrorEnum registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb)
    {
        return registTransactionCallback(user_address, cb, null);
    }

    public final net.platon.vm.slice.platon.ErrorEnum registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb)
    {
        return registerIR(ir_hash, cb, null);
    }

    public static Ice.DispatchStatus ___registTransactionCallback(TaskSession __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        String user_address;
        net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb;
        user_address = __is.readString();
        cb = net.platon.vm.slice.platon.callback.TransactionCallbackPrxHelper.__read(__is);
        __inS.endReadParams();
        net.platon.vm.slice.platon.ErrorEnum __ret = __obj.registTransactionCallback(user_address, cb, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        net.platon.vm.slice.platon.ErrorEnum.__write(__os, __ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___registerIR(TaskSession __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        String ir_hash;
        net.platon.vm.slice.platon.callback.TaskCallbackPrx cb;
        ir_hash = __is.readString();
        cb = net.platon.vm.slice.platon.callback.TaskCallbackPrxHelper.__read(__is);
        __inS.endReadParams();
        net.platon.vm.slice.platon.ErrorEnum __ret = __obj.registerIR(ir_hash, cb, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        net.platon.vm.slice.platon.ErrorEnum.__write(__os, __ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    private final static String[] __all =
    {
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "registTransactionCallback",
        "registerIR"
    };

    public Ice.DispatchStatus __dispatch(IceInternal.Incoming in, Ice.Current __current)
    {
        int pos = java.util.Arrays.binarySearch(__all, __current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return ___ice_id(this, in, __current);
            }
            case 1:
            {
                return ___ice_ids(this, in, __current);
            }
            case 2:
            {
                return ___ice_isA(this, in, __current);
            }
            case 3:
            {
                return ___ice_ping(this, in, __current);
            }
            case 4:
            {
                return ___registTransactionCallback(this, in, __current);
            }
            case 5:
            {
                return ___registerIR(this, in, __current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 0L;
}
