// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon.service;

public interface _TaskSessionOperations
{
    net.platon.vm.slice.platon.ErrorEnum registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, Ice.Current __current);

    net.platon.vm.slice.platon.ErrorEnum registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, Ice.Current __current);
}
