// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon.service;

/**
 * Provides type-specific helper functions.
 **/
public final class NodeChannelSessionPrxHelper extends Ice.ObjectPrxHelperBase implements NodeChannelSessionPrx
{
    private static final String __error_name = "error";

    public void error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error)
    {
        error(taskId, role, from, error, null, false);
    }

    public void error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx)
    {
        error(taskId, role, from, error, __ctx, true);
    }

    private void error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_error(begin_error(taskId, role, from, error, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error)
    {
        return begin_error(taskId, role, from, error, null, false, false, null);
    }

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx)
    {
        return begin_error(taskId, role, from, error, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, Ice.Callback __cb)
    {
        return begin_error(taskId, role, from, error, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_error(taskId, role, from, error, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, Callback_NodeChannelSession_error __cb)
    {
        return begin_error(taskId, role, from, error, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_error __cb)
    {
        return begin_error(taskId, role, from, error, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_error(String taskId, 
                                       net.platon.vm.slice.platon.MPCRole role, 
                                       String from, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_error(taskId, role, from, error, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_error(String taskId, 
                                       net.platon.vm.slice.platon.MPCRole role, 
                                       String from, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_error(taskId, role, from, error, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_error(String taskId, 
                                       net.platon.vm.slice.platon.MPCRole role, 
                                       String from, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_error(taskId, role, from, error, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_error(String taskId, 
                                       net.platon.vm.slice.platon.MPCRole role, 
                                       String from, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_error(taskId, role, from, error, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_error(String taskId, 
                                        net.platon.vm.slice.platon.MPCRole role, 
                                        String from, 
                                        net.platon.vm.slice.platon.ErrorEnum error, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_error(taskId, 
                           role, 
                           from, 
                           error, 
                           __ctx, 
                           __explicitCtx, 
                           __synchronous, 
                           new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_error(String taskId, 
                                        net.platon.vm.slice.platon.MPCRole role, 
                                        String from, 
                                        net.platon.vm.slice.platon.ErrorEnum error, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__error_name, __cb);
        try
        {
            __result.prepare(__error_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(taskId);
            net.platon.vm.slice.platon.MPCRole.__write(__os, role);
            __os.writeString(from);
            net.platon.vm.slice.platon.ErrorEnum.__write(__os, error);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_error(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __error_name);
    }

    private static final String __input_name = "input";

    public void input(byte[] data)
    {
        input(data, null, false);
    }

    public void input(byte[] data, java.util.Map<String, String> __ctx)
    {
        input(data, __ctx, true);
    }

    private void input(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_input(begin_input(data, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_input(byte[] data)
    {
        return begin_input(data, null, false, false, null);
    }

    public Ice.AsyncResult begin_input(byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_input(data, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_input(byte[] data, Ice.Callback __cb)
    {
        return begin_input(data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_input(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_input(data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_input(byte[] data, Callback_NodeChannelSession_input __cb)
    {
        return begin_input(data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_input(byte[] data, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_input __cb)
    {
        return begin_input(data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_input(byte[] data, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_input(data, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_input(byte[] data, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_input(data, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_input(byte[] data, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_input(data, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_input(byte[] data, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_input(data, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_input(byte[] data, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_input(data, 
                           __ctx, 
                           __explicitCtx, 
                           __synchronous, 
                           new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_input(byte[] data, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__input_name, __cb);
        try
        {
            __result.prepare(__input_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            net.platon.vm.slice.platon.ByteListHelper.write(__os, data);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_input(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __input_name);
    }

    private static final String __inputData_name = "inputData";

    public void inputData(String taskId, String fromUser, byte[] data)
    {
        inputData(taskId, fromUser, data, null, false);
    }

    public void inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx)
    {
        inputData(taskId, fromUser, data, __ctx, true);
    }

    private void inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_inputData(begin_inputData(taskId, fromUser, data, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data)
    {
        return begin_inputData(taskId, fromUser, data, null, false, false, null);
    }

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_inputData(taskId, fromUser, data, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, Ice.Callback __cb)
    {
        return begin_inputData(taskId, fromUser, data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_inputData(taskId, fromUser, data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, Callback_NodeChannelSession_inputData __cb)
    {
        return begin_inputData(taskId, fromUser, data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_inputData __cb)
    {
        return begin_inputData(taskId, fromUser, data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_inputData(String taskId, 
                                           String fromUser, 
                                           byte[] data, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_inputData(taskId, fromUser, data, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_inputData(String taskId, 
                                           String fromUser, 
                                           byte[] data, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_inputData(taskId, fromUser, data, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_inputData(String taskId, 
                                           String fromUser, 
                                           byte[] data, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_inputData(taskId, fromUser, data, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_inputData(String taskId, 
                                           String fromUser, 
                                           byte[] data, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_inputData(taskId, fromUser, data, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_inputData(String taskId, 
                                            String fromUser, 
                                            byte[] data, 
                                            java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_inputData(taskId, 
                               fromUser, 
                               data, 
                               __ctx, 
                               __explicitCtx, 
                               __synchronous, 
                               new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_inputData(String taskId, 
                                            String fromUser, 
                                            byte[] data, 
                                            java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__inputData_name, __cb);
        try
        {
            __result.prepare(__inputData_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(taskId);
            __os.writeString(fromUser);
            net.platon.vm.slice.platon.ByteListHelper.write(__os, data);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_inputData(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __inputData_name);
    }

    private static final String __invite_name = "invite";

    public void invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb)
    {
        invite(taskparams, cb, null, false);
    }

    public void invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx)
    {
        invite(taskparams, cb, __ctx, true);
    }

    private void invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_invite(begin_invite(taskparams, cb, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb)
    {
        return begin_invite(taskparams, cb, null, false, false, null);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx)
    {
        return begin_invite(taskparams, cb, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Callback __cb)
    {
        return begin_invite(taskparams, cb, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_invite(taskparams, cb, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Callback_NodeChannelSession_invite __cb)
    {
        return begin_invite(taskparams, cb, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_invite __cb)
    {
        return begin_invite(taskparams, cb, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_invite(taskparams, cb, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invite(taskparams, cb, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_invite(taskparams, cb, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invite(taskparams, cb, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                         net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invite(taskparams, 
                            cb, 
                            __ctx, 
                            __explicitCtx, 
                            __synchronous, 
                            new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                         net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__invite_name, __cb);
        try
        {
            __result.prepare(__invite_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            TaskParams.__write(__os, taskparams);
            net.platon.vm.slice.platon.callback.NodeCallbackPrxHelper.__write(__os, cb);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_invite(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __invite_name);
    }

    private static final String __invite2_name = "invite2";

    public int invite2(TaskParams taskparams)
    {
        return invite2(taskparams, null, false);
    }

    public int invite2(TaskParams taskparams, java.util.Map<String, String> __ctx)
    {
        return invite2(taskparams, __ctx, true);
    }

    private int invite2(TaskParams taskparams, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__invite2_name);
        return end_invite2(begin_invite2(taskparams, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams)
    {
        return begin_invite2(taskparams, null, false, false, null);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, java.util.Map<String, String> __ctx)
    {
        return begin_invite2(taskparams, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, Ice.Callback __cb)
    {
        return begin_invite2(taskparams, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_invite2(taskparams, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, Callback_NodeChannelSession_invite2 __cb)
    {
        return begin_invite2(taskparams, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_invite2 __cb)
    {
        return begin_invite2(taskparams, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_invite2(taskparams, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invite2(taskparams, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_invite2(taskparams, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invite2(taskparams, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_IntCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invite2(taskparams, __ctx, __explicitCtx, __synchronous, 
                             new IceInternal.Functional_TwowayCallbackInt(__responseCb, __exceptionCb, __sentCb)
                                 {
                                     public final void __completed(Ice.AsyncResult __result)
                                     {
                                         NodeChannelSessionPrxHelper.__invite2_completed(this, __result);
                                     }
                                 });
    }

    private Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__invite2_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__invite2_name, __cb);
        try
        {
            __result.prepare(__invite2_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            TaskParams.__write(__os, taskparams);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public int end_invite2(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __invite2_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __invite2_completed(Ice.TwowayCallbackInt __cb, Ice.AsyncResult __result)
    {
        net.platon.vm.slice.platon.service.NodeChannelSessionPrx __proxy = (net.platon.vm.slice.platon.service.NodeChannelSessionPrx)__result.getProxy();
        int __ret = 0;
        try
        {
            __ret = __proxy.end_invite2(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __notify_name = "notify";

    public void _notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb)
    {
        _notify(taskparams, cb, null, false);
    }

    public void _notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx)
    {
        _notify(taskparams, cb, __ctx, true);
    }

    private void _notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_notify(begin_notify(taskparams, cb, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb)
    {
        return begin_notify(taskparams, cb, null, false, false, null);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx)
    {
        return begin_notify(taskparams, cb, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Callback __cb)
    {
        return begin_notify(taskparams, cb, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_notify(taskparams, cb, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Callback_NodeChannelSession_notify __cb)
    {
        return begin_notify(taskparams, cb, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_notify __cb)
    {
        return begin_notify(taskparams, cb, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_notify(taskparams, cb, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_notify(taskparams, cb, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_notify(taskparams, cb, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_notify(taskparams, cb, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                         net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_notify(taskparams, 
                            cb, 
                            __ctx, 
                            __explicitCtx, 
                            __synchronous, 
                            new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                         net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__notify_name, __cb);
        try
        {
            __result.prepare(__notify_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            TaskParams.__write(__os, taskparams);
            net.platon.vm.slice.platon.callback.NodeCallbackPrxHelper.__write(__os, cb);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_notify(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __notify_name);
    }

    private static final String __notify2_name = "notify2";

    public int notify2(TaskParams taskparams)
    {
        return notify2(taskparams, null, false);
    }

    public int notify2(TaskParams taskparams, java.util.Map<String, String> __ctx)
    {
        return notify2(taskparams, __ctx, true);
    }

    private int notify2(TaskParams taskparams, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__notify2_name);
        return end_notify2(begin_notify2(taskparams, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams)
    {
        return begin_notify2(taskparams, null, false, false, null);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, java.util.Map<String, String> __ctx)
    {
        return begin_notify2(taskparams, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, Ice.Callback __cb)
    {
        return begin_notify2(taskparams, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_notify2(taskparams, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, Callback_NodeChannelSession_notify2 __cb)
    {
        return begin_notify2(taskparams, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_notify2 __cb)
    {
        return begin_notify2(taskparams, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_notify2(taskparams, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_notify2(taskparams, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_notify2(taskparams, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_notify2(taskparams, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_IntCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_notify2(taskparams, __ctx, __explicitCtx, __synchronous, 
                             new IceInternal.Functional_TwowayCallbackInt(__responseCb, __exceptionCb, __sentCb)
                                 {
                                     public final void __completed(Ice.AsyncResult __result)
                                     {
                                         NodeChannelSessionPrxHelper.__notify2_completed(this, __result);
                                     }
                                 });
    }

    private Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__notify2_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__notify2_name, __cb);
        try
        {
            __result.prepare(__notify2_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            TaskParams.__write(__os, taskparams);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public int end_notify2(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __notify2_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __notify2_completed(Ice.TwowayCallbackInt __cb, Ice.AsyncResult __result)
    {
        net.platon.vm.slice.platon.service.NodeChannelSessionPrx __proxy = (net.platon.vm.slice.platon.service.NodeChannelSessionPrx)__result.getProxy();
        int __ret = 0;
        try
        {
            __ret = __proxy.end_notify2(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __ready_name = "ready";

    public void ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb)
    {
        ready(taskparams, cb, null, false);
    }

    public void ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx)
    {
        ready(taskparams, cb, __ctx, true);
    }

    private void ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_ready(begin_ready(taskparams, cb, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb)
    {
        return begin_ready(taskparams, cb, null, false, false, null);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx)
    {
        return begin_ready(taskparams, cb, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Callback __cb)
    {
        return begin_ready(taskparams, cb, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_ready(taskparams, cb, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Callback_NodeChannelSession_ready __cb)
    {
        return begin_ready(taskparams, cb, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_ready __cb)
    {
        return begin_ready(taskparams, cb, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                       net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_ready(taskparams, cb, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                       net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_ready(taskparams, cb, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                       net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_ready(taskparams, cb, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                       net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_ready(taskparams, cb, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_ready(taskparams, 
                           cb, 
                           __ctx, 
                           __explicitCtx, 
                           __synchronous, 
                           new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__ready_name, __cb);
        try
        {
            __result.prepare(__ready_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            TaskParams.__write(__os, taskparams);
            net.platon.vm.slice.platon.callback.NodeCallbackPrxHelper.__write(__os, cb);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_ready(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __ready_name);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static NodeChannelSessionPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), NodeChannelSessionPrx.class, NodeChannelSessionPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static NodeChannelSessionPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), NodeChannelSessionPrx.class, NodeChannelSessionPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static NodeChannelSessionPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), NodeChannelSessionPrx.class, NodeChannelSessionPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static NodeChannelSessionPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), NodeChannelSessionPrx.class, NodeChannelSessionPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static NodeChannelSessionPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, NodeChannelSessionPrx.class, NodeChannelSessionPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static NodeChannelSessionPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, NodeChannelSessionPrx.class, NodeChannelSessionPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::platon::service::NodeChannelSession"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, NodeChannelSessionPrx v)
    {
        __os.writeProxy(v);
    }

    public static NodeChannelSessionPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            NodeChannelSessionPrxHelper result = new NodeChannelSessionPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
