// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon.service;

public interface NodeChannelSessionPrx extends Ice.ObjectPrx
{
    public void invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb);

    public void invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Callback __cb);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Callback_NodeChannelSession_invite __cb);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_invite __cb);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_invite(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_invite(Ice.AsyncResult __result);

    public void _notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb);

    public void _notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Callback __cb);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Callback_NodeChannelSession_notify __cb);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_notify __cb);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_notify(TaskParams taskparams, 
                                        net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_notify(Ice.AsyncResult __result);

    public int invite2(TaskParams taskparams);

    public int invite2(TaskParams taskparams, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, Ice.Callback __cb);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, Callback_NodeChannelSession_invite2 __cb);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_invite2 __cb);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_invite2(TaskParams taskparams, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public int end_invite2(Ice.AsyncResult __result);

    public int notify2(TaskParams taskparams);

    public int notify2(TaskParams taskparams, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, Ice.Callback __cb);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, Callback_NodeChannelSession_notify2 __cb);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_notify2 __cb);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_notify2(TaskParams taskparams, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public int end_notify2(Ice.AsyncResult __result);

    public void ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb);

    public void ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Ice.Callback __cb);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, Callback_NodeChannelSession_ready __cb);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_ready __cb);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                       net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                       net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                       net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_ready(TaskParams taskparams, 
                                       net.platon.vm.slice.platon.callback.NodeCallbackPrx cb, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_ready(Ice.AsyncResult __result);

    public void inputData(String taskId, String fromUser, byte[] data);

    public void inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data);

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, Callback_NodeChannelSession_inputData __cb);

    public Ice.AsyncResult begin_inputData(String taskId, String fromUser, byte[] data, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_inputData __cb);

    public Ice.AsyncResult begin_inputData(String taskId, 
                                           String fromUser, 
                                           byte[] data, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_inputData(String taskId, 
                                           String fromUser, 
                                           byte[] data, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_inputData(String taskId, 
                                           String fromUser, 
                                           byte[] data, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_inputData(String taskId, 
                                           String fromUser, 
                                           byte[] data, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public void end_inputData(Ice.AsyncResult __result);

    public void input(byte[] data);

    public void input(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_input(byte[] data);

    public Ice.AsyncResult begin_input(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_input(byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_input(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_input(byte[] data, Callback_NodeChannelSession_input __cb);

    public Ice.AsyncResult begin_input(byte[] data, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_input __cb);

    public Ice.AsyncResult begin_input(byte[] data, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_input(byte[] data, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_input(byte[] data, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_input(byte[] data, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_input(Ice.AsyncResult __result);

    public void error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error);

    public void error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error);

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, Ice.Callback __cb);

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, Callback_NodeChannelSession_error __cb);

    public Ice.AsyncResult begin_error(String taskId, net.platon.vm.slice.platon.MPCRole role, String from, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx, Callback_NodeChannelSession_error __cb);

    public Ice.AsyncResult begin_error(String taskId, 
                                       net.platon.vm.slice.platon.MPCRole role, 
                                       String from, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_error(String taskId, 
                                       net.platon.vm.slice.platon.MPCRole role, 
                                       String from, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_error(String taskId, 
                                       net.platon.vm.slice.platon.MPCRole role, 
                                       String from, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_error(String taskId, 
                                       net.platon.vm.slice.platon.MPCRole role, 
                                       String from, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_error(Ice.AsyncResult __result);
}
