// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon.service;

public interface TaskSessionPrx extends Ice.ObjectPrx
{
    public net.platon.vm.slice.platon.ErrorEnum registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb);

    public net.platon.vm.slice.platon.ErrorEnum registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, Ice.Callback __cb);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, Callback_TaskSession_registTransactionCallback __cb);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, java.util.Map<String, String> __ctx, Callback_TaskSession_registTransactionCallback __cb);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, 
                                                           net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, 
                                                           IceInternal.Functional_GenericCallback1<net.platon.vm.slice.platon.ErrorEnum> __responseCb, 
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, 
                                                           net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, 
                                                           IceInternal.Functional_GenericCallback1<net.platon.vm.slice.platon.ErrorEnum> __responseCb, 
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, 
                                                           net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, 
                                                           java.util.Map<String, String> __ctx, 
                                                           IceInternal.Functional_GenericCallback1<net.platon.vm.slice.platon.ErrorEnum> __responseCb, 
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_registTransactionCallback(String user_address, 
                                                           net.platon.vm.slice.platon.callback.TransactionCallbackPrx cb, 
                                                           java.util.Map<String, String> __ctx, 
                                                           IceInternal.Functional_GenericCallback1<net.platon.vm.slice.platon.ErrorEnum> __responseCb, 
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                           IceInternal.Functional_BoolCallback __sentCb);

    public net.platon.vm.slice.platon.ErrorEnum end_registTransactionCallback(Ice.AsyncResult __result);

    public net.platon.vm.slice.platon.ErrorEnum registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb);

    public net.platon.vm.slice.platon.ErrorEnum registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb);

    public Ice.AsyncResult begin_registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, Ice.Callback __cb);

    public Ice.AsyncResult begin_registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, Callback_TaskSession_registerIR __cb);

    public Ice.AsyncResult begin_registerIR(String ir_hash, net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, java.util.Map<String, String> __ctx, Callback_TaskSession_registerIR __cb);

    public Ice.AsyncResult begin_registerIR(String ir_hash, 
                                            net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, 
                                            IceInternal.Functional_GenericCallback1<net.platon.vm.slice.platon.ErrorEnum> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_registerIR(String ir_hash, 
                                            net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, 
                                            IceInternal.Functional_GenericCallback1<net.platon.vm.slice.platon.ErrorEnum> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_registerIR(String ir_hash, 
                                            net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<net.platon.vm.slice.platon.ErrorEnum> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_registerIR(String ir_hash, 
                                            net.platon.vm.slice.platon.callback.TaskCallbackPrx cb, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<net.platon.vm.slice.platon.ErrorEnum> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public net.platon.vm.slice.platon.ErrorEnum end_registerIR(Ice.AsyncResult __result);
}
