// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package abc.def.demo;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FooOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Foo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 i32 = 1;</code>
     */
    int getI32();

    /**
     * <code>float f = 2;</code>
     */
    float getF();
  }
  /**
   * Protobuf type {@code demo.Foo}
   */
  public  static final class Foo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Foo)
      FooOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Foo.newBuilder() to construct.
    private Foo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Foo() {
      i32_ = 0;
      f_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Foo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              i32_ = input.readInt32();
              break;
            }
            case 21: {

              f_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return abc.def.demo.Demo.internal_static_demo_Foo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return abc.def.demo.Demo.internal_static_demo_Foo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              abc.def.demo.Demo.Foo.class, abc.def.demo.Demo.Foo.Builder.class);
    }

    public static final int I32_FIELD_NUMBER = 1;
    private int i32_;
    /**
     * <code>int32 i32 = 1;</code>
     */
    public int getI32() {
      return i32_;
    }

    public static final int F_FIELD_NUMBER = 2;
    private float f_;
    /**
     * <code>float f = 2;</code>
     */
    public float getF() {
      return f_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (i32_ != 0) {
        output.writeInt32(1, i32_);
      }
      if (f_ != 0F) {
        output.writeFloat(2, f_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (i32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i32_);
      }
      if (f_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, f_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof abc.def.demo.Demo.Foo)) {
        return super.equals(obj);
      }
      abc.def.demo.Demo.Foo other = (abc.def.demo.Demo.Foo) obj;

      boolean result = true;
      result = result && (getI32()
          == other.getI32());
      result = result && (
          java.lang.Float.floatToIntBits(getF())
          == java.lang.Float.floatToIntBits(
              other.getF()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + I32_FIELD_NUMBER;
      hash = (53 * hash) + getI32();
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getF());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static abc.def.demo.Demo.Foo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static abc.def.demo.Demo.Foo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static abc.def.demo.Demo.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static abc.def.demo.Demo.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static abc.def.demo.Demo.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static abc.def.demo.Demo.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static abc.def.demo.Demo.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static abc.def.demo.Demo.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static abc.def.demo.Demo.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static abc.def.demo.Demo.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static abc.def.demo.Demo.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static abc.def.demo.Demo.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(abc.def.demo.Demo.Foo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Foo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Foo)
        abc.def.demo.Demo.FooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return abc.def.demo.Demo.internal_static_demo_Foo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return abc.def.demo.Demo.internal_static_demo_Foo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                abc.def.demo.Demo.Foo.class, abc.def.demo.Demo.Foo.Builder.class);
      }

      // Construct using abc.def.demo.Demo.Foo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        i32_ = 0;

        f_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return abc.def.demo.Demo.internal_static_demo_Foo_descriptor;
      }

      @java.lang.Override
      public abc.def.demo.Demo.Foo getDefaultInstanceForType() {
        return abc.def.demo.Demo.Foo.getDefaultInstance();
      }

      @java.lang.Override
      public abc.def.demo.Demo.Foo build() {
        abc.def.demo.Demo.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public abc.def.demo.Demo.Foo buildPartial() {
        abc.def.demo.Demo.Foo result = new abc.def.demo.Demo.Foo(this);
        result.i32_ = i32_;
        result.f_ = f_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof abc.def.demo.Demo.Foo) {
          return mergeFrom((abc.def.demo.Demo.Foo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(abc.def.demo.Demo.Foo other) {
        if (other == abc.def.demo.Demo.Foo.getDefaultInstance()) return this;
        if (other.getI32() != 0) {
          setI32(other.getI32());
        }
        if (other.getF() != 0F) {
          setF(other.getF());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        abc.def.demo.Demo.Foo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (abc.def.demo.Demo.Foo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int i32_ ;
      /**
       * <code>int32 i32 = 1;</code>
       */
      public int getI32() {
        return i32_;
      }
      /**
       * <code>int32 i32 = 1;</code>
       */
      public Builder setI32(int value) {
        
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i32 = 1;</code>
       */
      public Builder clearI32() {
        
        i32_ = 0;
        onChanged();
        return this;
      }

      private float f_ ;
      /**
       * <code>float f = 2;</code>
       */
      public float getF() {
        return f_;
      }
      /**
       * <code>float f = 2;</code>
       */
      public Builder setF(float value) {
        
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float f = 2;</code>
       */
      public Builder clearF() {
        
        f_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Foo)
    }

    // @@protoc_insertion_point(class_scope:demo.Foo)
    private static final abc.def.demo.Demo.Foo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new abc.def.demo.Demo.Foo();
    }

    public static abc.def.demo.Demo.Foo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Foo>
        PARSER = new com.google.protobuf.AbstractParser<Foo>() {
      @java.lang.Override
      public Foo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Foo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Foo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Foo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public abc.def.demo.Demo.Foo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Bar)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    boolean hasFoo();
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    abc.def.demo.Demo.Foo getFoo();
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    abc.def.demo.Demo.FooOrBuilder getFooOrBuilder();

    /**
     * <code>int32 i32 = 2;</code>
     */
    int getI32();

    /**
     * <code>float f = 3;</code>
     */
    float getF();
  }
  /**
   * Protobuf type {@code demo.Bar}
   */
  public  static final class Bar extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Bar)
      BarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Bar.newBuilder() to construct.
    private Bar(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bar() {
      i32_ = 0;
      f_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Bar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              abc.def.demo.Demo.Foo.Builder subBuilder = null;
              if (foo_ != null) {
                subBuilder = foo_.toBuilder();
              }
              foo_ = input.readMessage(abc.def.demo.Demo.Foo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(foo_);
                foo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              i32_ = input.readInt32();
              break;
            }
            case 29: {

              f_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return abc.def.demo.Demo.internal_static_demo_Bar_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return abc.def.demo.Demo.internal_static_demo_Bar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              abc.def.demo.Demo.Bar.class, abc.def.demo.Demo.Bar.Builder.class);
    }

    public static final int FOO_FIELD_NUMBER = 1;
    private abc.def.demo.Demo.Foo foo_;
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    public boolean hasFoo() {
      return foo_ != null;
    }
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    public abc.def.demo.Demo.Foo getFoo() {
      return foo_ == null ? abc.def.demo.Demo.Foo.getDefaultInstance() : foo_;
    }
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    public abc.def.demo.Demo.FooOrBuilder getFooOrBuilder() {
      return getFoo();
    }

    public static final int I32_FIELD_NUMBER = 2;
    private int i32_;
    /**
     * <code>int32 i32 = 2;</code>
     */
    public int getI32() {
      return i32_;
    }

    public static final int F_FIELD_NUMBER = 3;
    private float f_;
    /**
     * <code>float f = 3;</code>
     */
    public float getF() {
      return f_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (foo_ != null) {
        output.writeMessage(1, getFoo());
      }
      if (i32_ != 0) {
        output.writeInt32(2, i32_);
      }
      if (f_ != 0F) {
        output.writeFloat(3, f_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (foo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFoo());
      }
      if (i32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, i32_);
      }
      if (f_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, f_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof abc.def.demo.Demo.Bar)) {
        return super.equals(obj);
      }
      abc.def.demo.Demo.Bar other = (abc.def.demo.Demo.Bar) obj;

      boolean result = true;
      result = result && (hasFoo() == other.hasFoo());
      if (hasFoo()) {
        result = result && getFoo()
            .equals(other.getFoo());
      }
      result = result && (getI32()
          == other.getI32());
      result = result && (
          java.lang.Float.floatToIntBits(getF())
          == java.lang.Float.floatToIntBits(
              other.getF()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFoo()) {
        hash = (37 * hash) + FOO_FIELD_NUMBER;
        hash = (53 * hash) + getFoo().hashCode();
      }
      hash = (37 * hash) + I32_FIELD_NUMBER;
      hash = (53 * hash) + getI32();
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getF());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static abc.def.demo.Demo.Bar parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static abc.def.demo.Demo.Bar parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static abc.def.demo.Demo.Bar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static abc.def.demo.Demo.Bar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static abc.def.demo.Demo.Bar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static abc.def.demo.Demo.Bar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static abc.def.demo.Demo.Bar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static abc.def.demo.Demo.Bar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static abc.def.demo.Demo.Bar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static abc.def.demo.Demo.Bar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static abc.def.demo.Demo.Bar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static abc.def.demo.Demo.Bar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(abc.def.demo.Demo.Bar prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Bar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Bar)
        abc.def.demo.Demo.BarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return abc.def.demo.Demo.internal_static_demo_Bar_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return abc.def.demo.Demo.internal_static_demo_Bar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                abc.def.demo.Demo.Bar.class, abc.def.demo.Demo.Bar.Builder.class);
      }

      // Construct using abc.def.demo.Demo.Bar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fooBuilder_ == null) {
          foo_ = null;
        } else {
          foo_ = null;
          fooBuilder_ = null;
        }
        i32_ = 0;

        f_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return abc.def.demo.Demo.internal_static_demo_Bar_descriptor;
      }

      @java.lang.Override
      public abc.def.demo.Demo.Bar getDefaultInstanceForType() {
        return abc.def.demo.Demo.Bar.getDefaultInstance();
      }

      @java.lang.Override
      public abc.def.demo.Demo.Bar build() {
        abc.def.demo.Demo.Bar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public abc.def.demo.Demo.Bar buildPartial() {
        abc.def.demo.Demo.Bar result = new abc.def.demo.Demo.Bar(this);
        if (fooBuilder_ == null) {
          result.foo_ = foo_;
        } else {
          result.foo_ = fooBuilder_.build();
        }
        result.i32_ = i32_;
        result.f_ = f_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof abc.def.demo.Demo.Bar) {
          return mergeFrom((abc.def.demo.Demo.Bar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(abc.def.demo.Demo.Bar other) {
        if (other == abc.def.demo.Demo.Bar.getDefaultInstance()) return this;
        if (other.hasFoo()) {
          mergeFoo(other.getFoo());
        }
        if (other.getI32() != 0) {
          setI32(other.getI32());
        }
        if (other.getF() != 0F) {
          setF(other.getF());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        abc.def.demo.Demo.Bar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (abc.def.demo.Demo.Bar) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private abc.def.demo.Demo.Foo foo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          abc.def.demo.Demo.Foo, abc.def.demo.Demo.Foo.Builder, abc.def.demo.Demo.FooOrBuilder> fooBuilder_;
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public boolean hasFoo() {
        return fooBuilder_ != null || foo_ != null;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public abc.def.demo.Demo.Foo getFoo() {
        if (fooBuilder_ == null) {
          return foo_ == null ? abc.def.demo.Demo.Foo.getDefaultInstance() : foo_;
        } else {
          return fooBuilder_.getMessage();
        }
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public Builder setFoo(abc.def.demo.Demo.Foo value) {
        if (fooBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          foo_ = value;
          onChanged();
        } else {
          fooBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public Builder setFoo(
          abc.def.demo.Demo.Foo.Builder builderForValue) {
        if (fooBuilder_ == null) {
          foo_ = builderForValue.build();
          onChanged();
        } else {
          fooBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public Builder mergeFoo(abc.def.demo.Demo.Foo value) {
        if (fooBuilder_ == null) {
          if (foo_ != null) {
            foo_ =
              abc.def.demo.Demo.Foo.newBuilder(foo_).mergeFrom(value).buildPartial();
          } else {
            foo_ = value;
          }
          onChanged();
        } else {
          fooBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public Builder clearFoo() {
        if (fooBuilder_ == null) {
          foo_ = null;
          onChanged();
        } else {
          foo_ = null;
          fooBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public abc.def.demo.Demo.Foo.Builder getFooBuilder() {
        
        onChanged();
        return getFooFieldBuilder().getBuilder();
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public abc.def.demo.Demo.FooOrBuilder getFooOrBuilder() {
        if (fooBuilder_ != null) {
          return fooBuilder_.getMessageOrBuilder();
        } else {
          return foo_ == null ?
              abc.def.demo.Demo.Foo.getDefaultInstance() : foo_;
        }
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          abc.def.demo.Demo.Foo, abc.def.demo.Demo.Foo.Builder, abc.def.demo.Demo.FooOrBuilder> 
          getFooFieldBuilder() {
        if (fooBuilder_ == null) {
          fooBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              abc.def.demo.Demo.Foo, abc.def.demo.Demo.Foo.Builder, abc.def.demo.Demo.FooOrBuilder>(
                  getFoo(),
                  getParentForChildren(),
                  isClean());
          foo_ = null;
        }
        return fooBuilder_;
      }

      private int i32_ ;
      /**
       * <code>int32 i32 = 2;</code>
       */
      public int getI32() {
        return i32_;
      }
      /**
       * <code>int32 i32 = 2;</code>
       */
      public Builder setI32(int value) {
        
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i32 = 2;</code>
       */
      public Builder clearI32() {
        
        i32_ = 0;
        onChanged();
        return this;
      }

      private float f_ ;
      /**
       * <code>float f = 3;</code>
       */
      public float getF() {
        return f_;
      }
      /**
       * <code>float f = 3;</code>
       */
      public Builder setF(float value) {
        
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float f = 3;</code>
       */
      public Builder clearF() {
        
        f_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Bar)
    }

    // @@protoc_insertion_point(class_scope:demo.Bar)
    private static final abc.def.demo.Demo.Bar DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new abc.def.demo.Demo.Bar();
    }

    public static abc.def.demo.Demo.Bar getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bar>
        PARSER = new com.google.protobuf.AbstractParser<Bar>() {
      @java.lang.Override
      public Bar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bar(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bar> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bar> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public abc.def.demo.Demo.Bar getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Foo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Foo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Bar_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Bar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\004demo\"\035\n\003Foo\022\013\n\003i32\030\001 \001(\005\022\t" +
      "\n\001f\030\002 \001(\002\"5\n\003Bar\022\026\n\003foo\030\001 \001(\0132\t.demo.Foo" +
      "\022\013\n\003i32\030\002 \001(\005\022\t\n\001f\030\003 \001(\002B\016\n\014abc.def.demo" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_Foo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Foo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Foo_descriptor,
        new java.lang.String[] { "I32", "F", });
    internal_static_demo_Bar_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_Bar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Bar_descriptor,
        new java.lang.String[] { "Foo", "I32", "F", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
