// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `jugo_node_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.node.service;

public interface NodeSession extends Ice.Object,
                                     _NodeSessionOperations, _NodeSessionOperationsNC
{
    public static final String ice_staticId = "::service::NodeSession";

    public static final long serialVersionUID = -1198590594L;
}
