// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon;

public enum MPCRole implements java.io.Serializable
{
    
    PART_ALICE(1),
    
    PART_BOB(2),
    
    PART_GREEN(3),
    
    PART_NOBODY(4);

    public int
    value()
    {
        return __value;
    }

    public static MPCRole
    valueOf(int __v)
    {
        switch(__v)
        {
        case 1:
            return PART_ALICE;
        case 2:
            return PART_BOB;
        case 3:
            return PART_GREEN;
        case 4:
            return PART_NOBODY;
        }
        return null;
    }

    private
    MPCRole(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 4);
    }

    public static void
    __write(IceInternal.BasicStream __os, MPCRole __v)
    {
        if(__v == null)
        {
            __os.writeEnum(net.platon.vm.slice.platon.MPCRole.PART_ALICE.value(), 4);
        }
        else
        {
            __os.writeEnum(__v.value(), 4);
        }
    }

    public static MPCRole
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(4);
        return __validate(__v);
    }

    private static MPCRole
    __validate(int __v)
    {
        final MPCRole __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
