// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon;

public enum NodeCommunicateMode implements java.io.Serializable
{
    
    MCALLBACK(0),
    
    MSERVICE(1);

    public int
    value()
    {
        return __value;
    }

    public static NodeCommunicateMode
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return MCALLBACK;
        case 1:
            return MSERVICE;
        }
        return null;
    }

    private
    NodeCommunicateMode(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 1);
    }

    public static void
    __write(IceInternal.BasicStream __os, NodeCommunicateMode __v)
    {
        if(__v == null)
        {
            __os.writeEnum(net.platon.vm.slice.platon.NodeCommunicateMode.MCALLBACK.value(), 1);
        }
        else
        {
            __os.writeEnum(__v.value(), 1);
        }
    }

    public static NodeCommunicateMode
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(1);
        return __validate(__v);
    }

    private static NodeCommunicateMode
    __validate(int __v)
    {
        final NodeCommunicateMode __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
