// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mpctype.proto

package net.platon.vm.proto;

public final class Mpctype {
  private Mpctype() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MPCInteger32OrBuilder extends
      // @@protoc_insertion_point(interface_extends:mpctype.MPCInteger32)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 i32 = 1;</code>
     */
    int getI32();
  }
  /**
   * Protobuf type {@code mpctype.MPCInteger32}
   */
  public  static final class MPCInteger32 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mpctype.MPCInteger32)
      MPCInteger32OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MPCInteger32.newBuilder() to construct.
    private MPCInteger32(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MPCInteger32() {
      i32_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MPCInteger32(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              i32_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCInteger32_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCInteger32_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.platon.vm.proto.Mpctype.MPCInteger32.class, net.platon.vm.proto.Mpctype.MPCInteger32.Builder.class);
    }

    public static final int I32_FIELD_NUMBER = 1;
    private int i32_;
    /**
     * <code>int32 i32 = 1;</code>
     */
    public int getI32() {
      return i32_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (i32_ != 0) {
        output.writeInt32(1, i32_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (i32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i32_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.platon.vm.proto.Mpctype.MPCInteger32)) {
        return super.equals(obj);
      }
      net.platon.vm.proto.Mpctype.MPCInteger32 other = (net.platon.vm.proto.Mpctype.MPCInteger32) obj;

      boolean result = true;
      result = result && (getI32()
          == other.getI32());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + I32_FIELD_NUMBER;
      hash = (53 * hash) + getI32();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.platon.vm.proto.Mpctype.MPCInteger32 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.platon.vm.proto.Mpctype.MPCInteger32 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mpctype.MPCInteger32}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mpctype.MPCInteger32)
        net.platon.vm.proto.Mpctype.MPCInteger32OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCInteger32_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCInteger32_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.platon.vm.proto.Mpctype.MPCInteger32.class, net.platon.vm.proto.Mpctype.MPCInteger32.Builder.class);
      }

      // Construct using net.platon.vm.proto.Mpctype.MPCInteger32.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        i32_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCInteger32_descriptor;
      }

      @java.lang.Override
      public net.platon.vm.proto.Mpctype.MPCInteger32 getDefaultInstanceForType() {
        return net.platon.vm.proto.Mpctype.MPCInteger32.getDefaultInstance();
      }

      @java.lang.Override
      public net.platon.vm.proto.Mpctype.MPCInteger32 build() {
        net.platon.vm.proto.Mpctype.MPCInteger32 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.platon.vm.proto.Mpctype.MPCInteger32 buildPartial() {
        net.platon.vm.proto.Mpctype.MPCInteger32 result = new net.platon.vm.proto.Mpctype.MPCInteger32(this);
        result.i32_ = i32_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.platon.vm.proto.Mpctype.MPCInteger32) {
          return mergeFrom((net.platon.vm.proto.Mpctype.MPCInteger32)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.platon.vm.proto.Mpctype.MPCInteger32 other) {
        if (other == net.platon.vm.proto.Mpctype.MPCInteger32.getDefaultInstance()) return this;
        if (other.getI32() != 0) {
          setI32(other.getI32());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.platon.vm.proto.Mpctype.MPCInteger32 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.platon.vm.proto.Mpctype.MPCInteger32) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int i32_ ;
      /**
       * <code>int32 i32 = 1;</code>
       */
      public int getI32() {
        return i32_;
      }
      /**
       * <code>int32 i32 = 1;</code>
       */
      public Builder setI32(int value) {
        
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i32 = 1;</code>
       */
      public Builder clearI32() {
        
        i32_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mpctype.MPCInteger32)
    }

    // @@protoc_insertion_point(class_scope:mpctype.MPCInteger32)
    private static final net.platon.vm.proto.Mpctype.MPCInteger32 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.platon.vm.proto.Mpctype.MPCInteger32();
    }

    public static net.platon.vm.proto.Mpctype.MPCInteger32 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MPCInteger32>
        PARSER = new com.google.protobuf.AbstractParser<MPCInteger32>() {
      @java.lang.Override
      public MPCInteger32 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MPCInteger32(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MPCInteger32> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MPCInteger32> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.platon.vm.proto.Mpctype.MPCInteger32 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MPCFloatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mpctype.MPCFloat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float f = 1;</code>
     */
    float getF();
  }
  /**
   * Protobuf type {@code mpctype.MPCFloat}
   */
  public  static final class MPCFloat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mpctype.MPCFloat)
      MPCFloatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MPCFloat.newBuilder() to construct.
    private MPCFloat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MPCFloat() {
      f_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MPCFloat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              f_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCFloat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCFloat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.platon.vm.proto.Mpctype.MPCFloat.class, net.platon.vm.proto.Mpctype.MPCFloat.Builder.class);
    }

    public static final int F_FIELD_NUMBER = 1;
    private float f_;
    /**
     * <code>float f = 1;</code>
     */
    public float getF() {
      return f_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (f_ != 0F) {
        output.writeFloat(1, f_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (f_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, f_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.platon.vm.proto.Mpctype.MPCFloat)) {
        return super.equals(obj);
      }
      net.platon.vm.proto.Mpctype.MPCFloat other = (net.platon.vm.proto.Mpctype.MPCFloat) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getF())
          == java.lang.Float.floatToIntBits(
              other.getF()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getF());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.platon.vm.proto.Mpctype.MPCFloat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.platon.vm.proto.Mpctype.MPCFloat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mpctype.MPCFloat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mpctype.MPCFloat)
        net.platon.vm.proto.Mpctype.MPCFloatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCFloat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCFloat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.platon.vm.proto.Mpctype.MPCFloat.class, net.platon.vm.proto.Mpctype.MPCFloat.Builder.class);
      }

      // Construct using net.platon.vm.proto.Mpctype.MPCFloat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        f_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.platon.vm.proto.Mpctype.internal_static_mpctype_MPCFloat_descriptor;
      }

      @java.lang.Override
      public net.platon.vm.proto.Mpctype.MPCFloat getDefaultInstanceForType() {
        return net.platon.vm.proto.Mpctype.MPCFloat.getDefaultInstance();
      }

      @java.lang.Override
      public net.platon.vm.proto.Mpctype.MPCFloat build() {
        net.platon.vm.proto.Mpctype.MPCFloat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.platon.vm.proto.Mpctype.MPCFloat buildPartial() {
        net.platon.vm.proto.Mpctype.MPCFloat result = new net.platon.vm.proto.Mpctype.MPCFloat(this);
        result.f_ = f_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.platon.vm.proto.Mpctype.MPCFloat) {
          return mergeFrom((net.platon.vm.proto.Mpctype.MPCFloat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.platon.vm.proto.Mpctype.MPCFloat other) {
        if (other == net.platon.vm.proto.Mpctype.MPCFloat.getDefaultInstance()) return this;
        if (other.getF() != 0F) {
          setF(other.getF());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.platon.vm.proto.Mpctype.MPCFloat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.platon.vm.proto.Mpctype.MPCFloat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float f_ ;
      /**
       * <code>float f = 1;</code>
       */
      public float getF() {
        return f_;
      }
      /**
       * <code>float f = 1;</code>
       */
      public Builder setF(float value) {
        
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float f = 1;</code>
       */
      public Builder clearF() {
        
        f_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mpctype.MPCFloat)
    }

    // @@protoc_insertion_point(class_scope:mpctype.MPCFloat)
    private static final net.platon.vm.proto.Mpctype.MPCFloat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.platon.vm.proto.Mpctype.MPCFloat();
    }

    public static net.platon.vm.proto.Mpctype.MPCFloat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MPCFloat>
        PARSER = new com.google.protobuf.AbstractParser<MPCFloat>() {
      @java.lang.Override
      public MPCFloat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MPCFloat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MPCFloat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MPCFloat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.platon.vm.proto.Mpctype.MPCFloat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpctype_MPCInteger32_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mpctype_MPCInteger32_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpctype_MPCFloat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mpctype_MPCFloat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmpctype.proto\022\007mpctype\"\033\n\014MPCInteger32" +
      "\022\013\n\003i32\030\001 \001(\005\"\025\n\010MPCFloat\022\t\n\001f\030\001 \001(\002B\025\n\023" +
      "net.platon.vm.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mpctype_MPCInteger32_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mpctype_MPCInteger32_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mpctype_MPCInteger32_descriptor,
        new java.lang.String[] { "I32", });
    internal_static_mpctype_MPCFloat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mpctype_MPCFloat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mpctype_MPCFloat_descriptor,
        new java.lang.String[] { "F", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
