// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon.callback;

public interface TaskCallbackPrx extends Ice.ObjectPrx
{
    public void error(MpcRequest request, net.platon.vm.slice.platon.ErrorEnum error);

    public void error(MpcRequest request, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_error(MpcRequest request, net.platon.vm.slice.platon.ErrorEnum error);

    public Ice.AsyncResult begin_error(MpcRequest request, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_error(MpcRequest request, net.platon.vm.slice.platon.ErrorEnum error, Ice.Callback __cb);

    public Ice.AsyncResult begin_error(MpcRequest request, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_error(MpcRequest request, net.platon.vm.slice.platon.ErrorEnum error, Callback_TaskCallback_error __cb);

    public Ice.AsyncResult begin_error(MpcRequest request, net.platon.vm.slice.platon.ErrorEnum error, java.util.Map<String, String> __ctx, Callback_TaskCallback_error __cb);

    public Ice.AsyncResult begin_error(MpcRequest request, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_error(MpcRequest request, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_error(MpcRequest request, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_error(MpcRequest request, 
                                       net.platon.vm.slice.platon.ErrorEnum error, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_error(Ice.AsyncResult __result);

    public net.platon.vm.slice.platon.ErrorEnum inputData(MpcRequest request, net.platon.vm.slice.platon.ByteListHolder data, net.platon.vm.slice.platon.ByteListHolder data_default);

    public net.platon.vm.slice.platon.ErrorEnum inputData(MpcRequest request, net.platon.vm.slice.platon.ByteListHolder data, net.platon.vm.slice.platon.ByteListHolder data_default, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_inputData(MpcRequest request);

    public Ice.AsyncResult begin_inputData(MpcRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_inputData(MpcRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_inputData(MpcRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_inputData(MpcRequest request, Callback_TaskCallback_inputData __cb);

    public Ice.AsyncResult begin_inputData(MpcRequest request, java.util.Map<String, String> __ctx, Callback_TaskCallback_inputData __cb);

    public interface FunctionalCallback_TaskCallback_inputData_Response
    {
        void apply(net.platon.vm.slice.platon.ErrorEnum __ret, byte[] data, byte[] data_default);
    }

    public Ice.AsyncResult begin_inputData(MpcRequest request, 
                                           FunctionalCallback_TaskCallback_inputData_Response __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_inputData(MpcRequest request, 
                                           FunctionalCallback_TaskCallback_inputData_Response __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_inputData(MpcRequest request, 
                                           java.util.Map<String, String> __ctx, 
                                           FunctionalCallback_TaskCallback_inputData_Response __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_inputData(MpcRequest request, 
                                           java.util.Map<String, String> __ctx, 
                                           FunctionalCallback_TaskCallback_inputData_Response __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public net.platon.vm.slice.platon.ErrorEnum end_inputData(net.platon.vm.slice.platon.ByteListHolder data, net.platon.vm.slice.platon.ByteListHolder data_default, Ice.AsyncResult __result);

    public void result(MpcRequest request, byte[] data);

    public void result(MpcRequest request, byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_result(MpcRequest request, byte[] data);

    public Ice.AsyncResult begin_result(MpcRequest request, byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_result(MpcRequest request, byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_result(MpcRequest request, byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_result(MpcRequest request, byte[] data, Callback_TaskCallback_result __cb);

    public Ice.AsyncResult begin_result(MpcRequest request, byte[] data, java.util.Map<String, String> __ctx, Callback_TaskCallback_result __cb);

    public Ice.AsyncResult begin_result(MpcRequest request, 
                                        byte[] data, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_result(MpcRequest request, 
                                        byte[] data, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_result(MpcRequest request, 
                                        byte[] data, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_result(MpcRequest request, 
                                        byte[] data, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_result(Ice.AsyncResult __result);
}
