// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `platon_mpc_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.platon.vm.slice.platon.callback;

public interface TransactionCallback extends Ice.Object,
                                             _TransactionCallbackOperations, _TransactionCallbackOperationsNC
{
    public static final String ice_staticId = "::platon::callback::TransactionCallback";

    public static final long serialVersionUID = -21263119L;
}
